### PR TITLE
siegfried: support v1.5 id param

### PR DESCRIPTION
**Pull request by sevein**

### CODE REVIEW

**Comment by richardlehane** [comment]
You could speed this up without affecting results by removing the file tool check for text formats on unknowns. Since v1.2, sf does its own text matching (natively implementing the same algorithm that the file tool uses - https://github.com/richardlehane/characterize) so running file should be redundant.

**Comment by sevein** [comment]
That's awesome @richardlehane, thank you!

**Comment by richardlehane** [comment]
no worries. To make it even faster it would be great to explore using the `sf -fpr` flag when you get some time. The -fpr flag starts a simple unix socket server that implements archivematica's format policy registry. I did a pull request for the client code here: https://github.com/artefactual/archivematica-fpr-tools/pull/4. Probably a little bit of work here as you'd need to manage starting/restarting/shutting down the server, but you'd avoid constantly having to restart sf.

**Comment by sevein** [comment]
I think the plan is to make use of `sf -fpr` in Archivematica 1.6. I'm pretty excited about that. I guess in that case we'll need to start managing `sf -fpr` as a service dependency, similar to clamav, etc...

**Comment by sevein** [comment]
See #12.

**Pull request closed without merging**
